version: '3.8'

services:
  go_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "4000:8000"
    env_file:
      - ./backend/.env
  mysql:
    image: mysql:9.3
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  adminer:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - go_app
